'use strict';

const https = require('https');

function buildIssueBody(finding) {
  const lines = [
    `**Severity**: ${finding.severity}`,
    `**Category**: ${finding.category}`,
    `**File**: \`${finding.testFile || finding.ownerHint || 'unknown'}\``,
    '',
    '### Reproducer',
    finding.reproducer?.command ? `\`\`\`\n${finding.reproducer.command}\n\`\`\`` : '_not available_',
    '',
    '_Generated by [Healix](https://healix.dev)_',
  ];
  return lines.join('\n');
}

function postJson(hostname, path, token, body) {
  return new Promise((resolve, reject) => {
    const data = JSON.stringify(body);
    const options = {
      hostname,
      port: 443,
      path,
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(data),
        'Authorization': `Bearer ${token}`,
        'User-Agent': 'Healix-MCP/1.0',
        'Accept': 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
      },
    };
    const req = https.request(options, (res) => {
      let raw = '';
      res.on('data', (chunk) => { raw += chunk; });
      res.on('end', () => resolve({ statusCode: res.statusCode, body: raw }));
    });
    req.on('error', reject);
    req.setTimeout(15000, () => { req.destroy(new Error('github_request_timeout')); });
    req.write(data);
    req.end();
  });
}

async function dispatch(finding, config) {
  try {
    const { statusCode, body } = await postJson(
      'api.github.com',
      `/repos/${config.owner}/${config.repo}/issues`,
      config.token,
      {
        title: `[Healix ${finding.severity}] ${finding.title}`,
        body: buildIssueBody(finding),
        labels: ['healix', finding.category].filter(Boolean),
      }
    );
    if (statusCode === 201) {
      let issueNumber = null;
      try { issueNumber = JSON.parse(body).number; } catch { /* ok */ }
      return { ok: true, issueNumber };
    }
    return { ok: false, error: `github_http_${statusCode}` };
  } catch (err) {
    return { ok: false, error: err.message };
  }
}

module.exports = { dispatch };
