'use strict';

const https = require('https');
const { URL } = require('url');

function toBasicAuth(email, apiToken) {
  return Buffer.from(`${email}:${apiToken}`).toString('base64');
}

function buildAdfDescription(finding) {
  const lines = [
    `Severity: ${finding.severity}`,
    `Category: ${finding.category}`,
    `File: ${finding.testFile || finding.ownerHint || 'unknown'}`,
    '',
    finding.reproducer?.command ? `Reproducer: ${finding.reproducer.command}` : '',
    '',
    'Generated by Healix.',
  ].filter((l) => l !== undefined);

  return {
    type: 'doc',
    version: 1,
    content: [
      {
        type: 'paragraph',
        content: [{ type: 'text', text: lines.join('\n') }],
      },
    ],
  };
}

function postJson(baseUrl, path, auth, body) {
  return new Promise((resolve, reject) => {
    const parsed = new URL(baseUrl);
    const data = JSON.stringify(body);
    const options = {
      hostname: parsed.hostname,
      port: parsed.port || 443,
      path,
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(data),
        'Authorization': `Basic ${auth}`,
        'Accept': 'application/json',
      },
    };
    const req = https.request(options, (res) => {
      let raw = '';
      res.on('data', (chunk) => { raw += chunk; });
      res.on('end', () => resolve({ statusCode: res.statusCode, body: raw }));
    });
    req.on('error', reject);
    req.setTimeout(15000, () => { req.destroy(new Error('jira_request_timeout')); });
    req.write(data);
    req.end();
  });
}

async function dispatch(finding, config) {
  try {
    const auth = toBasicAuth(config.email, config.apiToken);
    const { statusCode, body } = await postJson(
      config.baseUrl,
      '/rest/api/3/issue',
      auth,
      {
        fields: {
          project: { key: config.project },
          summary: `[Healix ${finding.severity}] ${finding.title}`,
          description: buildAdfDescription(finding),
          issuetype: { name: 'Bug' },
        },
      }
    );
    if (statusCode === 201) {
      let issueKey = null;
      try { issueKey = JSON.parse(body).key; } catch { /* ok */ }
      return { ok: true, issueKey };
    }
    return { ok: false, error: `jira_http_${statusCode}` };
  } catch (err) {
    return { ok: false, error: err.message };
  }
}

module.exports = { dispatch };
